=begin
#currencyapi

#The currency APIs help you retrieve exchange rates and convert prices between currencies easily.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module CloudmersiveCurrencyApiClient
  VERSION = '2.0.1'
end
