=begin
#currencyapi

#The currency APIs help you retrieve exchange rates and convert prices between currencies easily.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveCurrencyApiClient::CurrencyExchangeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CurrencyExchangeApi' do
  before do
    # run before each test
    @instance = CloudmersiveCurrencyApiClient::CurrencyExchangeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CurrencyExchangeApi' do
    it 'should create an instance of CurrencyExchangeApi' do
      expect(@instance).to be_instance_of(CloudmersiveCurrencyApiClient::CurrencyExchangeApi)
    end
  end

  # unit tests for currency_exchange_convert_currency
  # Converts a price from the source currency into the destination currency
  # Automatically converts the price in the source currency into the destination currency using the latest available currency exchange rate data.
  # @param source Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
  # @param destination Destination currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
  # @param source_price Input price, such as 19.99 in source currency
  # @param [Hash] opts the optional parameters
  # @return [ConvertedCurrencyResult]
  describe 'currency_exchange_convert_currency test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for currency_exchange_get_available_currencies
  # Get a list of available currencies and corresponding countries
  # Enumerates available currencies and the countries that correspond to these currencies.
  # @param [Hash] opts the optional parameters
  # @return [AvailableCurrencyResponse]
  describe 'currency_exchange_get_available_currencies test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for currency_exchange_get_exchange_rate
  # Gets the exchange rate from the source currency into the destination currency
  # Automatically gets the exchange rate from the source currency into the destination currency using the latest available currency exchange rate data.
  # @param source Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
  # @param destination Destination currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
  # @param [Hash] opts the optional parameters
  # @return [ExchangeRateResult]
  describe 'currency_exchange_get_exchange_rate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
